services:
  comfyui-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: v5runpod-comfyuiworker:v1.0.0
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8188:8188"
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/workspace

    # command: >
    #   /bin/bash -c "dev/start_dev.sh"

    command: tail -f /dev/null
    # command: >
    #   /bin/bash -c "/workspace/.venv/bin/python /workspace/ComfyUI/main.py --listen 0.0.0.0 --port 8188 --disable-auto-launch"